### ISSUE TITLE
Allow another file extensions than .es6

### ISSUE THREAD

**Issue by YoannNovaxis** [es6-rails/es6-rails#3]
I actually work with a old version of angular that cannot understand .es6 file in local. (The gem work very well when I deploy the app by the assets pipeline)

It will be great if you can allow the file extension ".es6.js" so I will be able to test my app in local.

Thanks for your work and for your time.

**Comment by razorcd** [comment]
Hi @YoannNovaxis,

I created a new PR with the changes to enable transpiling `.es6.js` files too: https://github.com/es6-rails/es6-rails/pull/5

Please try it in your own Rails app using this temporary branch in your `Gemfile`:
```
gem 'es6-rails', :git => "git@github.com:razorcd/es6-rails.git", :branch => "es6_js_extension_for_assets_and_views"
```

Also, could you please tell me what version of Ruby and Rails are you using.

Thanks

**Comment by YoannNovaxis** [comment]
Thank you, I will try that !

My Ruby version is '2.3.1' and my Rails version is '4.2.6'

**Comment by YoannNovaxis** [comment]
It seems it doesn't work, I still have es6 classes in the js after transpiling.

**Comment by razorcd** [comment]
I am also working on adding this to the example Rails app that uses this `es6-rails` gem: https://github.com/es6-rails/es6-rails-example/pull/1
App works, just have to update the tests.

**Comment by razorcd** [comment]
I confirm that it is not transpiling the `.es6.js` at the moment. Will look into it more the next days.

**Comment by YoannNovaxis** [comment]
Thanks :-) I see that the file "assets_generator.rb" copy all the es6 code from .es6 files but not .es6.js, but I don't know much how generators works.

**Comment by razorcd** [comment]
it might be because Rails already parses `.js` files so it might not direct the `.es6.js` files to this gem anymore. I am not completely sure yet.

Feel free to create a PR if you can fix it, I will also look into it.

**Comment by YoannNovaxis** [comment]
Good, can you give access to the repository ? I got a permision denied.

**Comment by razorcd** [comment]
I invited you. check email

**Comment by razorcd** [comment]
I pushed an update on the branch. `.es6.js` works for `assets` now.
Still have to fix when `.es6.js` is in `views` and loaded remotely throw Ajax.

Please try. I assume you only use the es6 in `assets`, right?

**Comment by YoannNovaxis** [comment]
Good ! Yes, I only use the es6 in assets, I will try that now. Thanks.

**Comment by YoannNovaxis** [comment]
It doesn't work for me, maybe I do something wrong. When I rename the file with just '.es6' it works but '.es6.js' doesn't.

When I execute 'rake assets:precompile' with '.es6' extention the generated file contains no ES6 Javascript, all my ES6 javascripts have been correctly transpiled.
But when I rename '.es6.js' and execute again  'rake assets:precompile' the generated javascripts contains my ES6 code, the transpiling have not been applied.

**Comment by razorcd** [comment]
I just tried that command on an example app and it works. Both `.es6` and `.es6.js` files are transpiled from ES6 to ES5.
Make sure you rebuild all dependencies so it pulls the `gem` from GitHub branch again.

I will update the example app these days too.

**Comment by YoannNovaxis** [comment]
I dont understand why it still take 'Using es6-rails 0.3.1 from git@github.com:razorcd/es6-rails.git (at es6_js_extension_for_assets_and_views@3ad686b)' after I did 'bundle install'.

**Comment by YoannNovaxis** [comment]
It works ! Thanks ! I had to add the ref of your last commit :

gem 'es6-rails', :git => "git@github.com:razorcd/es6-rails.git", :branch => "es6_js_extension_for_assets_and_views", :ref => "d9b69c71023291a8f56be32fedd307b7878352b9"

It seems to be a known bug with gems update from github.

**Comment by razorcd** [comment]
it's not updating from github for some reason. It should be pulling version `3.4`.
try these commands:
```
gem uninstall es6-rails
gem cleanup es6-rails
even delete or update Gemfile.lock
``` 
I tried with the same `branch` and pulls 3.4. `assets` are transpiled correctly.

**Comment by YoannNovaxis** [comment]
I work well for me, thanks again !

Tell me when you will publish the news version of the gem.

**Comment by razorcd** [comment]
published.  You can use `gem 'es6-rails', '0.3.5'` now.
Enjoy!
